mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^open_src_projects/', include('open_src_projects.urls')),
    url(r'^admin/', admin.site.urls),
]

open_src_projects/urls.py
from django.conf.urls import url

from . import views

app_name = 'open_src_projects'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<project_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^add_project/$', views.add_project, name='add_project'),
    url(r'^(?P<project_id>[0-9]+)/add_comment/$', views.add_comment, name='add_comment'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

open_src_projects/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

class OpenSrcProject(models.Model):
    project_name = models.CharField(max_length=200)
    project_description = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date published')
    num_votes = models.IntegerField(default=0)

    def __str__(self):
        return self.project_name

class Comment(models.Model):
    project = models.ForeignKey(OpenSrcProject, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=1000)

    def __str__(self):
        return self.comment_text

polls/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

open_src_projects/forms.py
from django.forms import ModelForm
from .models import OpenSrcProject


class OpenSrcProjectForm(ModelForm):
    class Meta:
        model = OpenSrcProject
        exclude = ['pub_date', 'num_votes']

open_src_projects/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.urls import reverse
from django.views import generic
from django.template import RequestContext
from .forms import OpenSrcProjectForm
from django.utils import timezone


from .models import OpenSrcProject


class IndexView(generic.ListView):
    template_name = 'open_src_projects/index.html'
    context_object_name = 'latest_project_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return OpenSrcProject.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = OpenSrcProject
    template_name = 'open_src_projects/detail.html'



class ResultsView(generic.DetailView):
    model = OpenSrcProject
    template_name = 'open_src_projects/results.html'

def add_project(request):
    # Get the context from the request.
    context = RequestContext(request)

    # A HTTP POST?
    if request.method == 'POST':
        form = OpenSrcProjectForm(request.POST)

        # Have we been provided a valid form?
        if form.is_valid():
            # Save new project
            model_instance = form.save(commit=False)
            model_instance.pub_date = timezone.now()
            model_instance.save()
            return redirect('open_src_projects:index')
        else:
            # Print errors
            print form.errors
    else:
        form = OpenSrcProjectForm()

    return render(request, 'open_src_projects/add_project.html', {'form':form})

def vote(request, project_id):
    project = get_object_or_404(OpenSrcProject, pk=project_id)

    if request.method == 'POST':
        project.num_votes += 1
        project.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('open_src_projects:detail', args=(project.id,)))
    else:
        return render(request, 'open_src_projects/detail.html', {
            'open_src_project': project,
            'error_message': 'Something went wrong'
        })

def add_comment(request, project_id):
    context = RequestContext(request)
    project = get_object_or_404(OpenSrcProject, pk=project_id)

    if request.method == 'POST':
        project.comment_set.create(comment_text = request.POST['comment_text'])

        return HttpResponseRedirect(reverse('open_src_projects:detail', args=(project.id,)))
    else:
        return render(request, 'open_src_projects/detail.html', {
            'open_src_project': project,
            'error_message': 'Something went wrong'
        })

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

open_src_projects/templates/open_src_projects/add_project.html
        <h1>Add a Project</h1>

        <form action="{% url 'open_src_projects:add_project' %}" method="post">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.label }}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Create Project" />
        </form>

open_src_projects/templates/open_src_projects/detail.html
<h1>{{ object.project_name }}</h1>
<h2>{{ object.project_description }}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'open_src_projects:vote' object.id %}" method="post">
{% csrf_token %}
<input type="submit" value="Vote" />
</form>

<p>Num votes: {{ object.num_votes }} </p>

<form action="{% url 'open_src_projects:add_comment' object.id %}" method="post">
{% csrf_token %}
Comment: <input type="text" name="comment_text" id="{{object.id}}" />

<input type="submit" value="Add Comment" />
</form>

<p>Comments:</p>
{% for c in object.comment_set.all %}
   <li>{{ c.comment_text }}</li>
{% endfor %}

open_src_projects/templates/open_src_projects/index.html
<a href="{% url 'open_src_projects:add_project' %}">Add a New Project</a>

{% if latest_project_list %}
    <ul>
    {% for project in latest_project_list %}
        <li><a href="{% url 'open_src_projects:detail' project.id %}">{{ project.project_name }}</a></li>
        <p>{{ project.project_description }}</p>
    {% endfor %}
    </ul>
{% else %}
    <p>No projects yet.</p>
{% endif %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>